### ISSUE TITLE
Действия после отправки на печать и время до конца печати

### ISSUE THREAD

**Issue by Mordevolt** [ipcn/shui-slicers-plugin#1]
Спасибо большое за плагин!
1. не хватает опции закрывать окно автоматом после отправки на печать
2. при нажатии кнопки "ок" при выбранной опции "запустить печать" зачем то появляется возможность сохранить файл, кажется не очень логично
3. обратил внимание что на принтер не передается расчетное время печати, таким образом виджет часов при печати может отображать только прошедшее с момента старта время. при нажатии на часы вместо ожидаемой продолжительности показываются нули.

Возможно это зависит от версии куры, у меня 5.1 бета

**Comment by 3dbaxtep** [comment]
1,2 исправлено в новой версии

**Comment by ipcn** [comment]
Окно передачи файлов изменено в версии v22.11.20. это решило проблемы 1 и 2.
Проблема 3 решается на стороне принтера и правильными настройками слайсера.
В прошивке SHUI от 2022-12-06 для этого добавлены дополнительные возможности:
https://github.com/vyacheslav-shubin/shui/blob/master/readme.txt#L1858
