### ISSUE TITLE
Принтер не отправляет на печать

### ISSUE THREAD

**Issue by kintolayli** [ipcn/shui-slicers-plugin#2]
Предыдущая версия работала, иногда выдавала ошибку Network Error, но все же лечилось иногда перезагрузкой принтера. Сейчас, после обновления плагина на версию [v22.11.20](https://github.com/ipcn/shui-slicers-plugin/releases/tag/22.11.20), появилась вот такая ошибка
![2022-12-07_02-37-39](https://user-images.githubusercontent.com/43316003/206048944-d9847459-521a-4e5f-92a6-bad866a8b154.png)
В чем может быть причина? Принтер правильно настроен и подключен по правильному адресу.

**Comment by ipcn** [comment]
Ошибка NetworkError говорит о невозможности передать данные на принтер по разным причинам, включая неправильные настройки адреса, проблемы с сетью и промежуточными узлами сети, а также проблемы на стороне принтера.  В данном случае ошибка на стороне принтера, который не может принять переданные ему данные, нужно обращаться к разработчику прошивки принтера.
